### ISSUE TITLE
Unable to start azkaban-web-server

### ISSUE THREAD

**Issue by right2code** [azkaban/azkaban#1592]
When i run azkaban i get the following error:

Using Hadoop from /opt/cloudera/parcels/CDH/lib/hadoop
./bin/..
:./bin/../lib/activation-1.1.jar:./bin/../lib/antlr-2.7.2.jar:./bin/../lib/azkaban-common-0.1.0-SNAPSHOT.jar:./bin/../lib/azkaban-web-server-0.1.0-SNAPSHOT.jar:./bin/../lib/c3p0-0.9.1.1.jar:./bin/../lib/cglib-nodep-2.2.jar:./bin/../lib/commons-beanutils-1.7.0.jar:./bin/../lib/commons-chain-1.1.jar:./bin/../lib/commons-codec-1.6.jar:./bin/../lib/commons-collections-3.2.2.jar:./bin/../lib/commons-compress-1.2.jar:./bin/../lib/commons-dbcp-1.4.jar:./bin/../lib/commons-dbutils-1.5.jar:./bin/../lib/commons-digester-1.8.jar:./bin/../lib/commons-fileupload-1.2.1.jar:./bin/../lib/commons-io-2.4.jar:./bin/../lib/commons-jexl-2.1.1.jar:./bin/../lib/commons-lang-2.6.jar:./bin/../lib/commons-logging-1.1.3.jar:./bin/../lib/commons-math3-3.0.jar:./bin/../lib/commons-pool-1.5.4.jar:./bin/../lib/commons-validator-1.3.1.jar:./bin/../lib/data-1.15.7.jar:./bin/../lib/data-transform-1.15.7.jar:./bin/../lib/dom4j-1.1.jar:./bin/../lib/guava-13.0.1.jar:./bin/../lib/httpclient-4.3.1.jar:./bin/../lib/httpcore-4.3.jar:./bin/../lib/jackson-core-2.2.2.jar:./bin/../lib/jackson-core-asl-1.9.5.jar:./bin/../lib/jackson-mapper-asl-1.9.5.jar:./bin/../lib/javax.inject-1.jar:./bin/../lib/javax.servlet-api-3.0.1.jar:./bin/../lib/jetty-6.1.26.jar:./bin/../lib/jetty-util-6.1.26.jar:./bin/../lib/joda-time-2.0.jar:./bin/../lib/jopt-simple-4.3.jar:./bin/../lib/json-20070829.jar:./bin/../lib/li-jersey-uri-1.15.7.jar:./bin/../lib/log4j-1.2.16.jar:./bin/../lib/mail-1.4.5.jar:./bin/../lib/mina-core-1.1.7.jar:./bin/../lib/mysql-connector-java-5.1.28.jar:./bin/../lib/netty-3.2.3.Final.jar:./bin/../lib/oro-2.0.8.jar:./bin/../lib/parseq-1.3.6.jar:./bin/../lib/pegasus-common-1.15.7.jar:./bin/../lib/quartz-2.2.1.jar:./bin/../lib/r2-1.15.7.jar:./bin/../lib/restli-common-1.15.7.jar:./bin/../lib/restli-server-1.15.7.jar:./bin/../lib/servlet-api-2.5-20081211.jar:./bin/../lib/servlet-api-2.5.jar:./bin/../lib/snappy-0.3.jar:./bin/../lib/sslext-1.2-0.jar:./bin/../lib/struts-core-1.3.8.jar:./bin/../lib/struts-taglib-1.3.8.jar:./bin/../lib/struts-tiles-1.3.8.jar:./bin/../lib/velocity-1.7.jar:./bin/../lib/velocity-tools-2.0.jar:./bin/../extlib/mysql-connector-java-5.1.39.jar:./bin/../plugins/*/*.jar:/opt/cloudera/parcels/CDH/lib/hadoop/conf:/opt/cloudera/parcels/CDH/lib/hadoop/*
./bin/azkaban-web-start.sh: line 53: print: command not found
[root@edge01 azkaban-web-server]# 2017-12-26 00:55:24.077:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
Exception in thread "main" azkaban.executor.ExecutorManagerException: Error fetching executor localhost:12321
	at azkaban.executor.JdbcExecutorLoader.fetchExecutor(JdbcExecutorLoader.java:862)
	at azkaban.executor.ExecutorManager.setupExecutors(ExecutorManager.java:203)
	at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:126)
	at azkaban.webapp.AzkabanWebServer.loadExecutorManager(AzkabanWebServer.java:261)
	at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:197)
	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:739)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.apache.commons.dbutils.AbstractQueryRunner.prepareConnection(AbstractQueryRunner.java:175)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:286)
	at azkaban.executor.JdbcExecutorLoader.fetchExecutor(JdbcExecutorLoader.java:854)
	... 5 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2575)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2311)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:347)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 10 more
Caused by: java.lang.NullPointerException
	at com.mysql.jdbc.ConnectionImpl.getServerCharacterEncoding(ConnectionImpl.java:3286)
	at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1987)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1913)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1290)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2493)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2526)
	... 24 more

**My azkaban.properties file:**

jetty.keystore=conf/keystore
jetty.password=keystorePass
jetty.keypassword=jettyKeyPass
jetty.truststore=conf/keystore
jetty.trustpassword=keystorePass
database.type=mysql
mysql.port=3306
mysql.host=localhost
mysql.database=azkaban
mysql.user=azkaban
mysql.password=ska_fZjf,3dX
mysql.numconnections=100
executor.maxThreads=50
executor.port=12321
executor.host=localhost
#executor.shared.token=abcdefg
executor.flow.threads=30
user.manager.class=azkaban.user.XmlUserManager
user.manager.xml.file=conf/azkaban-users.xml
jetty.maxThreads=25
jetty.ssl.port=8443
web.resource.dir=web/
jetty.hostname=localhost
jetty.port=8443
jetty.use.ssl=false

I think azkaban is having problems connecting to mysql db but i don't know why. Can anyone help me with this please?

**Comment by sridharpothamsetti** [comment]
Add this content in properties file

executor.global.properties=conf/global.properties
azkaban.project.dir=projects

and create empty global.properties file in conf directory and give a try

**Comment by ezhouyang** [comment]
If you use mysql8 that you must use mysql-connector-java-8.0.11.jar put in extlib dir.
Please check you lib dir && remove mysql-connector-java-5.1.28.jar.
Done it.

**Comment by astraydog** [comment]
> If you use mysql8 that you must use mysql-connector-java-8.0.11.jar put in extlib dir.
> Please check you lib dir && remove mysql-connector-java-5.1.28.jar.
> Done it.
I download mysql-connector-java-8.0.17.jar and put this jar into '/home/azkaban/azkaban/azkaban-exec-server/build/distributions/azkaban-exec-server-3.91.0-4-gb468bffe/lib'
but it still fails :
ERROR [StdOutErrRedirect] [main] [Azkaban] Loading class `com.mysql.jdbc.Driver'. 
This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. 
The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
