### ISSUE TITLE
FlowRunnerManager doesn't initialize this.active from DB

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#2243]
If an existing azkaban-executor is quickly terminated (so that it doesn't remove itself from the DB), and is then started again, it will find itself being already in the DB, and not touch the DB entry in `executors` table. This means that azkaban-web will continue dispatching executions to this executor. However, FlowRunnerManager's `active` field is not initialized based on the DB.

In https://github.com/azkaban/azkaban/pull/2133 FlowRunnerManager was changed to check for `this.active == true`, and if not, throw an `ExecutorManagerException` with the message `executor became inactive before setting up the flow`.

I think `FlowRunnerManager.active` should be initialized from the DB before `AzkabanExecutorServer.start()`.

**Comment by juhoautio** [comment]
@burgerkingeater, please check this, as https://github.com/azkaban/azkaban/pull/2133 was your PR.

**Comment by juhoautio** [comment]
@burgerkingeater could you comment?

Otherwise, @djaiswal83 & co., do you have anything to say on this? I can also make a PR to propose a fix if you like.

**Comment by juhoautio** [comment]
ping @burgerkingeater @jamiesjc

**Comment by burgerkingeater** [comment]
@juhoautio thanks for reporting this issue. `If an existing azkaban-executor is quickly terminated (so that it doesn't remove itself from the DB), and is then started again, it will find itself being already in the DB,` each time executor starts, a new port is assigned, so why do you think this is the case?

**Comment by juhoautio** [comment]
> each time executor starts, a new port is assigned, so why do you think this is the case?

Port can be a fixed one:

https://github.com/azkaban/azkaban/blob/e6b62f34609c7f50c64bb56b76327f4686ed13bd/az-core/src/main/java/azkaban/Constants.java#L190-L191

I'm not really familiar with the dynamic executor port feature.

**Comment by burgerkingeater** [comment]
@juhoautio got it, i think what you proposed makes sense. I'm happy to review your PR if any.

**Comment by juhoautio-rovio** [comment]
I think this is fixed since https://github.com/azkaban/azkaban/pull/2288. Only works if `executor.port` is configured with a static value though.

**Comment by saibalpatra** [comment]
This issue is still happening with Tag 3.90.0

I never had this issue before. Is there any fix for this?

**Comment by saibalpatra** [comment]
curl http://<executor-hostname>:<executor-port>/executor?action=activate fixes it. However I think this is a hack.
